[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
check-manifest = ">=0.25"
# Pytest-invenio 3 breaks the test with:
# ModuleNotFoundError: No module named 'flask_sqlalchemy.session'
pytest-invenio = "<3"
flask-pytest = "*"
# Avoid pytest>=8 as dependency resolution is not giving a compatible version of pluggy
# Manifests as: https://github.com/pytest-dev/pytest/issues/12144
pytest = "<8"
freezegun = "*"
docker-services-cli = "*"

[packages]
invenio-app-rdm = {extras = ["opensearch2"], version = "~=12.0.0"}
mex-invenio = {editable = true, path="./site"}
# mex-model version has implications for rendering so breaking changes should be considered carefully
mex-model = "4.1.0"
uwsgi = ">=2.0"
uwsgitop = ">=0.11"
uwsgi-tools = ">=1.1.1"
boto3 = "*"
dotenv = "*"

[requires]
python_version = "3.11"

[pipenv]
allow_prereleases = false
